apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default 
roleRef: 
  kind: ClusterRole
  name: secret-clusterrole
  apiGroup: rbac.authorization.k8s.io